FROM python:3.11-slim

WORKDIR /app

COPY ./app ./app
COPY ./tests ./tests
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install pytest httpx

CMD ["pytest", "--maxfail=1", "--disable-warnings", "-v", "tests"]
